package mwcli

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Noswad123/mind-weaver/internal/infra/db"
	"github.com/urfave/cli/v2"
)

type syncConflictReviewItem struct {
	ID            int64   `json:"id"`
	EntityType    string  `json:"entity_type"`
	EntityKey     string  `json:"entity_key"`
	Reason        string  `json:"reason"`
	CreatedAt     string  `json:"created_at"`
	ResolvedAt    *string `json:"resolved_at,omitempty"`
	LocalPayload  string  `json:"local_payload,omitempty"`
	RemotePayload string  `json:"remote_payload,omitempty"`
}

type syncConflictReviewReport struct {
	GeneratedAt    string                   `json:"generated_at"`
	OlderThan      string                   `json:"older_than"`
	CutoffTime     string                   `json:"cutoff_time"`
	UnresolvedOnly bool                     `json:"unresolved_only"`
	Limit          int                      `json:"limit"`
	ConflictCount  int                      `json:"conflict_count"`
	ExportFile     string                   `json:"export_file,omitempty"`
	ResolvedCount  int                      `json:"resolved_count,omitempty"`
	Conflicts      []syncConflictReviewItem `json:"conflicts"`
}

func buildSyncConflictsCommand(d deps) *cli.Command {
	return &cli.Command{
		Name:  "conflicts",
		Usage: "Review and export locally persisted sync conflicts",
		Subcommands: []*cli.Command{
			{
				Name:  "review",
				Usage: "Review stale conflicts, optionally export and mark resolved",
				Flags: []cli.Flag{
					&cli.StringFlag{
						Name:  "format",
						Usage: "Output format: text|json",
						Value: "text",
					},
					&cli.IntFlag{
						Name:  "limit",
						Usage: "Maximum number of conflicts to include",
						Value: 100,
					},
					&cli.DurationFlag{
						Name:  "older-than",
						Usage: "Only include conflicts older than this duration",
						Value: 7 * 24 * time.Hour,
					},
					&cli.BoolFlag{
						Name:  "include-resolved",
						Usage: "Include conflicts that are already resolved",
					},
					&cli.StringFlag{
						Name:  "export-file",
						Usage: "Write JSON export to this file path",
					},
					&cli.StringFlag{
						Name:  "export-dir",
						Usage: "Directory for autogenerated JSON export file",
						Value: filepath.Join(defaultConflictDir(), "reviews"),
					},
					&cli.BoolFlag{
						Name:  "mark-resolved",
						Usage: "Mark included conflicts resolved after successful export",
					},
				},
				Action: d.action(func(c *cli.Context, d deps) error {
					return withNoteDb(d.cfg, func(noteDb *db.NoteDb) error {
						olderThan := c.Duration("older-than")
						if olderThan <= 0 {
							return fmt.Errorf("older-than must be > 0")
						}

						cutoff := time.Now().UTC().Add(-olderThan)
						rows, err := noteDb.ListSyncConflictsByFilter(c.Context, db.SyncConflictFilter{
							Limit:          c.Int("limit"),
							UnresolvedOnly: !c.Bool("include-resolved"),
							CreatedBefore:  &cutoff,
						})
						if err != nil {
							return fmt.Errorf("list sync conflicts for review: %w", err)
						}

						report := buildSyncConflictReviewReport(rows, olderThan, cutoff, !c.Bool("include-resolved"), c.Int("limit"))

						exportPath, err := resolveSyncConflictExportPath(c.String("export-file"), c.String("export-dir"))
						if err != nil {
							return err
						}

						if c.Bool("mark-resolved") && exportPath == "" {
							return fmt.Errorf("mark-resolved requires export-file or export-dir")
						}

						if exportPath != "" {
							if err := writeSyncConflictReviewExport(exportPath, report); err != nil {
								return err
							}
							report.ExportFile = exportPath
						}

						if c.Bool("mark-resolved") && len(rows) > 0 {
							ids := make([]int64, 0, len(rows))
							for _, row := range rows {
								if row.ResolvedAt.Valid {
									continue
								}
								ids = append(ids, row.ID)
							}
							if err := noteDb.MarkSyncConflictsResolved(c.Context, ids, time.Now().UTC()); err != nil {
								return fmt.Errorf("mark sync conflicts resolved: %w", err)
							}
							report.ResolvedCount = len(ids)
						}

						switch strings.ToLower(strings.TrimSpace(c.String("format"))) {
						case "json":
							b, err := json.MarshalIndent(report, "", "  ")
							if err != nil {
								return fmt.Errorf("marshal conflict review report json: %w", err)
							}
							fmt.Println(string(b))
							return nil
						case "text", "":
							printSyncConflictReviewTextReport(report)
							return nil
						default:
							return fmt.Errorf("unsupported format %q (expected text|json)", c.String("format"))
						}
					})
				}),
			},
		},
	}
}

func buildSyncConflictReviewReport(rows []db.SyncConflictRow, olderThan time.Duration, cutoff time.Time, unresolvedOnly bool, limit int) syncConflictReviewReport {
	items := make([]syncConflictReviewItem, 0, len(rows))
	for _, row := range rows {
		var resolvedAt *string
		if row.ResolvedAt.Valid {
			value := row.ResolvedAt.String
			resolvedAt = &value
		}

		items = append(items, syncConflictReviewItem{
			ID:            row.ID,
			EntityType:    row.EntityType,
			EntityKey:     row.EntityKey,
			Reason:        row.Reason,
			CreatedAt:     row.CreatedAt,
			ResolvedAt:    resolvedAt,
			LocalPayload:  row.LocalPayload,
			RemotePayload: row.RemotePayload,
		})
	}

	return syncConflictReviewReport{
		GeneratedAt:    time.Now().UTC().Format(time.RFC3339),
		OlderThan:      olderThan.String(),
		CutoffTime:     cutoff.UTC().Format(time.RFC3339),
		UnresolvedOnly: unresolvedOnly,
		Limit:          limit,
		ConflictCount:  len(items),
		Conflicts:      items,
	}
}

func resolveSyncConflictExportPath(exportFile, exportDir string) (string, error) {
	exportFile = strings.TrimSpace(exportFile)
	if exportFile != "" {
		return exportFile, nil
	}

	exportDir = strings.TrimSpace(exportDir)
	if exportDir == "" {
		return "", nil
	}

	filename := fmt.Sprintf("sync-conflict-review-%s.json", time.Now().UTC().Format("20060102T150405Z"))
	return filepath.Join(exportDir, filename), nil
}

func writeSyncConflictReviewExport(path string, report syncConflictReviewReport) error {
	path = strings.TrimSpace(path)
	if path == "" {
		return fmt.Errorf("export path is required")
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create sync conflict review export directory: %w", err)
	}

	b, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal sync conflict review export: %w", err)
	}

	if err := os.WriteFile(path, append(b, '\n'), 0o644); err != nil {
		return fmt.Errorf("write sync conflict review export: %w", err)
	}

	return nil
}

func printSyncConflictReviewTextReport(report syncConflictReviewReport) {
	fmt.Printf("🧾 sync conflict review (%s)\n", report.GeneratedAt)
	fmt.Printf("cutoff:      %s (older than %s)\n", report.CutoffTime, report.OlderThan)
	fmt.Printf("unresolved:  %t\n", report.UnresolvedOnly)
	fmt.Printf("limit:       %d\n", report.Limit)
	fmt.Printf("conflicts:   %d\n", report.ConflictCount)
	if strings.TrimSpace(report.ExportFile) != "" {
		fmt.Printf("export file: %s\n", report.ExportFile)
	}
	if report.ResolvedCount > 0 {
		fmt.Printf("resolved:    %d\n", report.ResolvedCount)
	}

	if len(report.Conflicts) == 0 {
		fmt.Printf("\nEntries\n  - none\n")
		return
	}

	fmt.Printf("\nEntries\n")
	for _, conflict := range report.Conflicts {
		status := "unresolved"
		if conflict.ResolvedAt != nil && strings.TrimSpace(*conflict.ResolvedAt) != "" {
			status = "resolved"
		}
		fmt.Printf("  - id=%d type=%s key=%s reason=%s created=%s status=%s\n",
			conflict.ID,
			conflict.EntityType,
			conflict.EntityKey,
			conflict.Reason,
			conflict.CreatedAt,
			status,
		)
	}
}
